# Generated by Django 5.1.1 on 2024-09-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=155, unique=True),
            preserve_default=False,
        ),
    ]
